classes:
 - Bells
 - Birds
 - Cat_fights_and_moans
 - Chicken_coop
 - Cicadas_and_crickets
 - Crows_seagulls_and_magpies
 - Dog_barkings_and_howlings
 - Glass_breaking
 - Horn
 - Jet_aircrafts
 - Lawn_mower_brush_cutter_and_olive_shaker
 - Music
 - Propeller_aircrafts
 - Sirens_and_alarms
 - Thunder_fireworks_and_gunshot
 - Train
 - Vacuum_cleaner_fan_and_hair_dryer
 - Vehicle_idling
 - Vehicle_pass-by
 - Voices
 - Wind_turbine
 - Workshop
patience: 10
epochs: 100
batch_size: 128
sampling_rate: 52100
ref: 2.e-05
noise_perc: 0.3
seed: 1
valid_cut_secs:
 - 1
 - 2
 - 3
 - 4
 - 5
train_size: 500
es_size: 100
valid_size: 100
test_size: 100
