classes:
 - Music
 - Voices
 - Birds
patience: 10
epochs: 100
batch_size: 128
sampling_rate: 52100
ref: 2.e-05
noise_perc: 0.3
seed: 1
valid_cut_secs: [15, 20, 30]
train_size: 150
es_size: 50
valid_size: 50
test_size: 50
