classes:
 - Music
 - Voices
 - Birds
patience: 10
epochs: 100
batch_size: 128
sampling_rate: 52100
ref: 2.e-05
noise_perc: 0.3
seed: 1
valid_cut_secs: [1, 3, 5]
train_size: 10
es_size: 20
valid_size: 20
test_size: 20
